### ISSUE TITLE
Suggestion for improving Publication Date

### ISSUE THREAD

**Issue by jsjoeio** [jaydanurwin/astro-minimal-starter#2]
Hey! First, thanks for making this template. I'm using it to make my own personal template for static sites and I appreciate all the work you've done (especially for SEO).

In my readings online, I've read that Google has some [suggestions around publication dates](https://developers.google.com/search/docs/advanced/appearance/publication-dates). They suggest using labels like "Published" or "Last Updated".

Would you accept a PR to change [this](https://github.com/jaydanurwin/astro-minimal-starter/blob/main/src/components/BlogPostPreview.astro#L13) to this:

```svelte
function publishDateToMachineFriendlyDate(publishDate) {
  return new Date(publishDate).toISOString()
}

const machineFriendlyDate = publishDateToMachineFriendlyDate(publishDate)

---
    <p>Last updated: <time datetime={machineFriendlyDate}>{publishDate}</time></p
```

**Comment by jaydanurwin** [comment]
Hey Joe, thanks for the kind words and chiming in with suggestions! Although this is a good suggestion I think it might be too opinionated of a change to assume for everyone. I might take that suggestion for my own personal blog but I went through about 5 blogs I regularly read and none of them had "Last Updated" or "Published" in front of the date. Even [Google's own blog](https://www.blog.google/) doesn't follow this format surprisingly.

**Comment by jsjoeio** [comment]
Fair point! Wow, that's ironic 😅 well thank you for hearing my idea and sharing your thoughts. I'll close this for now then.
