### ISSUE TITLE
Suggestion for Open Graph URL to use canonicalURL

### ISSUE THREAD

**Issue by jsjoeio** [jaydanurwin/astro-minimal-starter#3]
The other tip I've heard is that the OpenGraph URL should match the canonical URL. 

Here's [one source](https://ahrefs.com/blog/open-graph-meta-tags/) from Ahrefs:
![image](https://user-images.githubusercontent.com/3806031/146494210-7124c9cc-e317-4ab5-ad40-a2dba8a185d6.png)

We would fix it here: https://github.com/jaydanurwin/astro-minimal-starter/blob/main/src/components/BaseHead.astro#L36

What do you think?

**Comment by jaydanurwin** [comment]
This is a great suggestion! I can open a PR and get that updated 👍🏼
