### ISSUE TITLE
Add a general page layout

### ISSUE THREAD

**Issue by thagxt** [jaydanurwin/astro-minimal-starter#5]
I'd like to suggest an enhancement:

It could be very useful to also add a "general layout" page for things like About, Legal, Contact pages etc.  
That way a part from the blog/posts you also have and example on how to create other pages on your website.
I think for someone just starting this would be a big help to understand how to make other pages as well.

p.s. For instance `ArticleSchema.jsx` is good for posts but not for other type of pages...

Thank you.

**Comment by thagxt** [comment]
The `<title>` currently displays only the title of the blog/page, there's no option to set the "Site name".
e.g. `Blog post title - MyWebsite`

**Comment by thagxt** [comment]
Only the first 10 posts are displayed on `/blog/`... and there's no pagination links to navigate to the next page.

**Comment by thagxt** [comment]
Missing layout for 404 page

**Comment by jaydanurwin** [comment]
> I'd like to suggest an enhancement:
> 
> It could be very useful to also add a "general layout" page for things like About, Legal, Contact pages etc. That way a part from the blog/posts you also have and example on how to create other pages on your website. I think for someone just starting this would be a big help to understand how to make other pages as well.
> 
> p.s. For instance `ArticleSchema.jsx` is good for posts but not for other type of pages...
> 
> Thank you.

I wanted to keep this starter extremely minimal but I do have plans to create a more fleshed out starter with styles and sub pages like you've listed here. Keep your eyes peeled for that to release early next year!

> The `<title>` currently displays only the title of the blog/page, there's no option to set the "Site name". e.g. `Blog post title - MyWebsite`

This one is actually already built into the starter. Go to `src/data/site.js` and change the information as needed.

> Only the first 10 posts are displayed on `/blog/`... and there's no pagination links to navigate to the next page.

If you'd like to open another issue and start on a PR for pagination feel free! I just haven't had the time to add that quite yet.

> Missing layout for 404 page

I'll get a basic 404 page added today 👍🏼 

Thanks for all of your suggestions @thagxt I'm always open to input and people opening new issues that will improve these starters for everyone!
